#include "core/skin_pixel_math.hpp"

#include <cstdint>
#include <cstdio>
#include <vector>

#include "doctest.h"

using namespace VoxelEngine;

namespace {
// Reference values were generated by an independent Python port of the Godot
// 4.7 engine math (PCG32 + RandomPCG::randf with float significand rounding
// and Image uint8 conversions), seeded 20240829 like the original GDScript.

constexpr uint32_t kExpectedU32[10] = {3622311839u, 2791358526u, 1712297112u, 937972366u, 95658826u,
                                       504314219u, 837645396u, 489647579u, 3507810941u, 740782379u};

constexpr double kExpectedRandf[6] = {0.64991378784179688, 0.35919436812400818, 0.019294368103146553,
                                      0.15350124239921570, 0.67247682809829712, 0.65736818313598633};

// First row (x = 0..63) of the 64x64 noise map's red bytes.
constexpr uint8_t kNoiseRow0[64] = {165, 91, 4,  39, 171, 167, 124, 177, 85, 32,  73,  229, 45,  178, 52,  39,
                                    134, 143, 16, 15, 98,  212, 78,  118, 51, 72,  95,  139, 40,  113, 213, 161,
                                    22,  75,  116, 62, 112, 178, 148, 143, 74, 114, 63,  68,  112, 30,  101, 188,
                                    53,  238, 237, 108, 96,  178, 230, 35, 172, 213, 72,  199, 252, 67,  218, 61};

struct NoisePix {
    int x;
    int y;
    int value;
};

constexpr NoisePix kNoisePix[] = {{0, 0, 165}, {1, 0, 91}, {2, 1, 173}, {5, 7, 89}, {63, 63, 192}};

constexpr uint32_t kNoiseMapFnv = 3267918385u;

constexpr uint8_t kGrayBase[16] = {10, 20, 30, 255, 40, 50, 60, 255, 200, 210, 220, 255, 0, 128, 255, 255};
constexpr uint8_t kGrayNoise[16] = {30, 120, 200, 250, 5, 99, 77, 180, 240, 66, 33, 210, 128, 255, 1, 11};

constexpr uint8_t kGrayOut_0147[16] = {0, 0, 1, 255, 37, 47, 57, 255, 221, 231, 241, 255, 36, 164, 255, 255};
constexpr uint8_t kGrayOut_0500[16] = {0, 0, 0, 255, 32, 42, 52, 255, 255, 255, 255, 255, 122, 250, 255, 255};
constexpr uint8_t kGrayOut_0123[16] = {0, 0, 6, 255, 38, 48, 58, 255, 217, 227, 237, 255, 30, 158, 255, 255};

// Full 64x64 pipe: deterministic checkerboard base + map noise @ amount 0.147.
constexpr uint32_t kFull64OutFnv = 3849895860u;
constexpr uint8_t kFull64OutHead[16] = {11, 11, 11, 255, 2, 2, 2, 255, 0, 0, 0, 255, 12, 12, 12, 255};
constexpr uint8_t kFull64OutTail[16] = {92, 92, 92, 255, 109, 109, 109, 255, 166, 166, 166, 255, 185, 185, 185, 255};

uint32_t fnv1a(const uint8_t* data, size_t len) {
    uint32_t h = 2166136261u;
    for (size_t i = 0; i < len; ++i) {
        h ^= data[i];
        h *= 16777619u;
    }
    return h;
}

// Mirrors `Image.set_pixel`: uint8_t(CLAMP(float_chan * 255.0, 0, 255)).
uint8_t byte_from_chan(float q) {
    const double v = static_cast<double>(q) * 255.0;
    return v <= 0.0 ? 0u : (v >= 255.0 ? 255u : static_cast<uint8_t>(v));
}
} // namespace

TEST_CASE("godot pcg: raw u32 stream matches the engine for seed 20240829") {
    GodotRng rng;
    rng.seed(20240829u);
    for (uint32_t e : kExpectedU32) {
        CHECK(rng.next_u32() == e);
    }
}

TEST_CASE("godot pcg: randf stream matches the engine (float-rounded significand)") {
    GodotRng rng;
    rng.seed(20240829u);
    for (double e : kExpectedRandf) {
        CHECK(rng.randf() == doctest::Approx(e).epsilon(1e-12));
    }
}

TEST_CASE("godot pcg: always in [0, 1)") {
    GodotRng rng;
    rng.seed(12345u);
    for (int i = 0; i < 4096; ++i) {
        const double v = rng.randf();
        CHECK(v >= 0.0);
        CHECK(v < 1.0);
    }
}

TEST_CASE("noise map: red bytes match the GDScript image byte for byte") {
    GodotRng rng;
    rng.seed(20240829u);
    uint8_t map[64 * 64];
    uint32_t fnv = 2166136261u;
    for (int y = 0; y < 64; ++y) {
        for (int x = 0; x < 64; ++x) {
            const double q = rng.randf();
            const uint8_t b = byte_from_chan(static_cast<float>(q));
            map[y * 64 + x] = b;
            fnv ^= b;
            fnv *= 16777619u;
        }
    }
    CHECK(fnv == kNoiseMapFnv);
    for (int x = 0; x < 64; ++x) {
        CHECK(map[x] == kNoiseRow0[x]);
    }
    for (const NoisePix& p : kNoisePix) {
        CHECK(map[p.y * 64 + p.x] == static_cast<uint8_t>(p.value));
    }
}

TEST_CASE("gray noise: 2x2 byte reference (amount 0.147 / 0.5 / 0.123)") {
    uint8_t out[16];
    for (int ch = 0; ch < 16; ++ch) {
        out[ch] = kGrayBase[ch];
    }
    apply_gray_noise_8(out, 4, kGrayNoise, 0.147);
    for (int ch = 0; ch < 16; ++ch) {
        CHECK(out[ch] == kGrayOut_0147[ch]);
    }

    for (int ch = 0; ch < 16; ++ch) {
        out[ch] = kGrayBase[ch];
    }
    apply_gray_noise_8(out, 4, kGrayNoise, 0.5);
    for (int ch = 0; ch < 16; ++ch) {
        CHECK(out[ch] == kGrayOut_0500[ch]);
    }

    for (int ch = 0; ch < 16; ++ch) {
        out[ch] = kGrayBase[ch];
    }
    apply_gray_noise_8(out, 4, kGrayNoise, 0.123);
    for (int ch = 0; ch < 16; ++ch) {
        CHECK(out[ch] == kGrayOut_0123[ch]);
    }
}

TEST_CASE("gray noise: full 64x64 pipe checksum matches the Python reference") {
    GodotRng rng;
    rng.seed(20240829u);
    std::vector<uint8_t> noise_r(64 * 64);
    for (size_t t = 0; t < noise_r.size(); ++t) {
        noise_r[t] = byte_from_chan(static_cast<float>(rng.randf()));
    }

    std::vector<uint8_t> out(64 * 64 * 4);
    for (int y = 0; y < 64; ++y) {
        for (int x = 0; x < 64; ++x) {
            const uint8_t g = static_cast<uint8_t>((x * 13 + y * 7) % 256);
            const size_t o = static_cast<size_t>(y * 64 + x) * 4;
            out[o] = g;
            out[o + 1] = g;
            out[o + 2] = g;
            out[o + 3] = 255;
        }
    }
    apply_gray_noise_8(out.data(), 64 * 64, noise_r.data(), 0.147);

    CHECK(fnv1a(out.data(), out.size()) == kFull64OutFnv);
    for (int ch = 0; ch < 16; ++ch) {
        CHECK(out[ch] == kFull64OutHead[ch]);
        CHECK(out[4000 + ch] == kFull64OutTail[ch]);
    }
}

TEST_CASE("uv texel bounds: mirrors the fill_uv_rect clamping") {
    auto uv = [](double lx, double ly, double hx, double hy, int dim) {
        return uv_texel_range(lx, ly, hx, hy, dim);
    };

    // Full UV box -> whole image.
    const TexelRange full = uv(0.0, 0.0, 1.0, 1.0, 64);
    CHECK(full.valid());
    CHECK(full.x0 == 0);
    CHECK(full.y0 == 0);
    CHECK(full.x1 == 63);
    CHECK(full.y1 == 63);

    // Empty rect at a single UV point.
    const TexelRange point = uv(0.5, 0.5, 0.5, 0.5, 64);
    CHECK(!point.valid());

    // Partial box.
    const TexelRange part = uv(0.1, 0.1, 0.2, 0.2, 64);
    CHECK(part.valid());
    CHECK(part.x0 == 6);
    CHECK(part.y0 == 6);
    CHECK(part.x1 == 12);
    CHECK(part.y1 == 12);

    // Edge-anchored quarter.
    const TexelRange quarter = uv(0.0, 0.0, 0.25, 1.0, 64);
    CHECK(quarter.valid());
    CHECK(quarter.x0 == 0);
    CHECK(quarter.x1 == 15);
    CHECK(quarter.y1 == 63);

    // Inverted box is empty after clamping.
    const TexelRange inverted = uv(0.8, 0.0, 0.4, 0.0, 64);
    CHECK(!inverted.valid());

    // Clamping stays inside the image and tolerates UV overshoot.
    const TexelRange over = uv(-0.5, -5.0, 2.0, 1.5, 64);
    CHECK(over.valid());
    CHECK(over.x0 == 0);
    CHECK(over.y0 == 0);
    CHECK(over.x1 == 63);
    CHECK(over.y1 == 63);
}